apiVersion: v1
kind: Namespace 
metadata: 
  name: netbox-community
---
apiVersion: v1
kind: LimitRange
metadata:
  name: default
  namespace: netbox-community
spec:
  limits:
  - default:
      cpu: "100m"
      memory: "128Mi"
    defaultRequest:
      cpu: "50m"
      memory: "64Mi"
    type: Container
